# Generated by Django 5.0.6 on 2024-06-28 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SuppliesPetCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=512, verbose_name="عنوان")),
                (
                    "image",
                    models.ImageField(upload_to="product/", verbose_name="تصویر"),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
            ],
            options={
                "verbose_name": "دسته بندی ها",
                "verbose_name_plural": "دسته بندی",
            },
        ),
        migrations.CreateModel(
            name="SuppliesPetProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=512, verbose_name="عنوان")),
                (
                    "description",
                    models.TextField(max_length=1024, verbose_name="توضیحات"),
                ),
                ("color", models.CharField(max_length=512, verbose_name="رنگ محصول")),
                (
                    "unit",
                    models.CharField(
                        blank=True, max_length=512, null=True, verbose_name="وزن"
                    ),
                ),
                ("price", models.PositiveIntegerField(verbose_name="قیمت")),
                (
                    "made_by_country",
                    models.CharField(max_length=256, verbose_name="ساخت کشور"),
                ),
                (
                    "is_available",
                    models.BooleanField(
                        default=True, verbose_name="موجود در انبار هست/نیست"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplies_pet_category",
                        to="product.suppliespetcategory",
                        verbose_name="دسته بندی",
                    ),
                ),
            ],
            options={
                "verbose_name": "لوازم جانبی",
                "verbose_name_plural": "لوازم جانبی ها",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="SuppliesPetImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="product/supplies_image/", verbose_name="تصویر"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplies_pet_image",
                        to="product.suppliespetproduct",
                        verbose_name="محصول",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SuppliesPetDiscount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "discount_price",
                    models.PositiveIntegerField(verbose_name="قیمت ویژه"),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplies_pet_product",
                        to="product.suppliespetproduct",
                        verbose_name="محصول",
                    ),
                ),
            ],
            options={
                "verbose_name": "محصول تخفیف \u200cدار",
                "verbose_name_plural": "محصولات تخفیف \u200cدار",
            },
        ),
        migrations.CreateModel(
            name="ProductVisit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip", models.CharField(max_length=32, verbose_name="آی پی کاربر")),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="productvisit",
                        to="product.suppliespetproduct",
                        verbose_name="محصول",
                    ),
                ),
            ],
            options={
                "verbose_name": "بازدید محصولات",
                "verbose_name_plural": "بازدید های محصولات",
            },
        ),
    ]
