# Generated by Django 5.0.6 on 2024-06-08 11:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="suppliespetdiscount",
            options={
                "verbose_name": "محصول تخفیف \u200cدار",
                "verbose_name_plural": "محصولات تخفیف \u200cدار",
            },
        ),
    ]
