# Generated by Django 5.0.6 on 2024-06-10 16:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0002_alter_suppliespetdiscount_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="suppliespetproduct",
            options={
                "ordering": ["-created"],
                "verbose_name": "لوازم جانبی",
                "verbose_name_plural": "لوازم جانبی ها",
            },
        ),
        migrations.AddField(
            model_name="suppliespetproduct",
            name="is_available",
            field=models.BooleanField(
                default=True, verbose_name="موجود در انبار هست/نیست"
            ),
        ),
    ]
