# Generated by Django 5.0.6 on 2024-06-11 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0004_productvisit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productvisit",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="productvisit",
                to="product.suppliespetproduct",
                verbose_name="محصول",
            ),
        ),
    ]
