# Generated by Django 5.0.6 on 2024-06-11 17:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0005_alter_productvisit_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="suppliespetdiscount",
            name="discount_price",
            field=models.PositiveIntegerField(verbose_name="قیمت ویژه"),
        ),
        migrations.AlterField(
            model_name="suppliespetproduct",
            name="price",
            field=models.PositiveIntegerField(verbose_name="قیمت"),
        ),
    ]
