# Generated by Django 5.0.6 on 2024-06-04 11:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_user_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
