# Generated by Django 5.0.6 on 2024-06-28 14:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=256, verbose_name="عنوان")),
            ],
        ),
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128, verbose_name="عنوان")),
                (
                    "description",
                    models.TextField(max_length=4096, verbose_name="توضیحات"),
                ),
                (
                    "aparat_video_link",
                    models.URLField(max_length=1024, verbose_name="لینک ویدیو آپارات"),
                ),
                ("image", models.ImageField(upload_to="blog/", verbose_name="تصویر")),
                (
                    "product",
                    models.ManyToManyField(
                        blank=True,
                        to="product.suppliespetproduct",
                        verbose_name="محصولات مرتبط",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, to="blog.blogtag", verbose_name="تگ ها"
                    ),
                ),
            ],
            options={
                "verbose_name": "Blog",
                "verbose_name_plural": "Blogs",
                "ordering": ["-id"],
            },
        ),
    ]
