# Generated by Django 5.0.6 on 2024-07-15 14:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={
                "ordering": ["-id"],
                "verbose_name": "بلاگ",
                "verbose_name_plural": "بلاگ",
            },
        ),
        migrations.AlterModelOptions(
            name="blogtag",
            options={"verbose_name": "بلاگ تگ", "verbose_name_plural": "بلاگ تگ"},
        ),
    ]
