# Generated by Django 5.0.6 on 2024-06-10 15:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
        ("product", "0002_alter_suppliespetdiscount_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="product",
            field=models.ManyToManyField(
                to="product.suppliespetproduct", verbose_name="محصولات مرتبط"
            ),
        ),
    ]
