# Generated by Django 5.0.6 on 2024-06-10 15:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_blog_product"),
        ("product", "0002_alter_suppliespetdiscount_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="product",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                to="product.suppliespetproduct",
                verbose_name="محصولات مرتبط",
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="tags",
            field=models.ManyToManyField(
                blank=True, null=True, to="blog.blogtag", verbose_name="تگ ها"
            ),
        ),
    ]
