# Generated by Django 5.0.6 on 2024-06-11 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PetFood",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="عنوان یا نام غذای خود را در این بخش وارد کنید",
                        max_length=256,
                        verbose_name="عنوان",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="توضیحات و شرح جزییات غذای خود را در این بخش بنویسید",
                        max_length=4096,
                        verbose_name="توضیحات",
                    ),
                ),
                (
                    "unit",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="مقدار به کیلو یا گرم بنویسید و عدد صحیح یا اعشاری بنویسید!",
                        max_digits=9,
                        max_length=256,
                        verbose_name="واحد اندازه بسته غذا",
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(
                        default=True, verbose_name="غذا موجود هست/نیست"
                    ),
                ),
            ],
            options={
                "verbose_name": "غذا",
                "verbose_name_plural": "غذاها",
            },
        ),
        migrations.CreateModel(
            name="PetFoodImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="home/Pet_Food/", verbose_name="تصویر"),
                ),
                (
                    "food",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.petfood",
                        verbose_name="غذا",
                    ),
                ),
            ],
        ),
    ]
