# Generated by Django 5.0.6 on 2024-06-11 17:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="petfood",
            name="price",
            field=models.PositiveIntegerField(default=212, verbose_name="قیمت"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="petfood",
            name="unit",
            field=models.DecimalField(
                decimal_places=4,
                help_text="مقدار به کیلو یا گرم بنویسید و عدد صحیح یا اعشاری بنویسید!",
                max_digits=9,
                verbose_name="واحد اندازه بسته غذا",
            ),
        ),
    ]
