# Generated by Django 5.0.6 on 2024-06-18 22:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_petfood_price_alter_petfood_unit"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="petfood",
            options={
                "ordering": ["-id"],
                "verbose_name": "غذا",
                "verbose_name_plural": "غذاها",
            },
        ),
        migrations.AlterModelOptions(
            name="petfoodimage",
            options={
                "verbose_name": "تصاویر غذا",
                "verbose_name_plural": "تصاویر غذاها",
            },
        ),
    ]
