# Generated by Django 5.0.6 on 2024-06-04 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AboutUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=256, verbose_name="Subject")),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="site_settings/about/"
                    ),
                ),
                ("body", models.TextField()),
            ],
            options={
                "verbose_name_plural": "About_Us",
            },
        ),
        migrations.CreateModel(
            name="ContactUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.CharField(max_length=15, verbose_name="Phone")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "instagram",
                    models.CharField(max_length=60, verbose_name="Instagram"),
                ),
                ("address", models.TextField(verbose_name="Address")),
            ],
            options={
                "verbose_name_plural": "Contact_Us",
            },
        ),
        migrations.CreateModel(
            name="ContactUsBody",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=256, verbose_name="Title")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="site_settings/contact/",
                        verbose_name="Image",
                    ),
                ),
                ("body", models.TextField(verbose_name="Body")),
                (
                    "contact_us",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="site_settings.contactus",
                        verbose_name="Contact_US",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Contact_Body",
            },
        ),
    ]
