# Generated by Django 5.0.6 on 2024-06-06 17:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AboutUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.TextField(max_length=1024, verbose_name="آدرس")),
                (
                    "description",
                    models.TextField(max_length=4096, verbose_name="توضیحات"),
                ),
            ],
            options={
                "verbose_name_plural": "About_Us",
            },
        ),
        migrations.CreateModel(
            name="CleaningServicePet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "haircut",
                    models.TextField(
                        max_length=4096, verbose_name="توضیحات کوتاه کردن مو سگ و گربه"
                    ),
                ),
                (
                    "nail_trimming",
                    models.TextField(
                        max_length=4096,
                        verbose_name="توضیحات کوتاه کردن ناخن سگ و گربه",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContactUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.CharField(max_length=16, verbose_name="Phone")),
                ("email", models.EmailField(max_length=256, verbose_name="Email")),
                (
                    "instagram",
                    models.CharField(max_length=256, verbose_name="Instagram"),
                ),
                (
                    "whats_app",
                    models.CharField(max_length=256, verbose_name="Whats App"),
                ),
                ("telegram", models.CharField(max_length=256, verbose_name="Telegram")),
            ],
            options={
                "verbose_name_plural": "Contact_Us",
            },
        ),
    ]
