# Generated by Django 5.0.6 on 2024-06-04 12:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("site_settings", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aboutus",
            name="body",
        ),
        migrations.RemoveField(
            model_name="aboutus",
            name="image",
        ),
        migrations.RemoveField(
            model_name="aboutus",
            name="title",
        ),
        migrations.RemoveField(
            model_name="contactus",
            name="address",
        ),
        migrations.AddField(
            model_name="aboutus",
            name="address",
            field=models.TextField(default=1, max_length=1024, verbose_name="آدرس"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="aboutus",
            name="description",
            field=models.TextField(
                default=333, max_length=4096, verbose_name="توضیحات"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contactus",
            name="telegram",
            field=models.CharField(default=13, max_length=256, verbose_name="Telegram"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contactus",
            name="whats_app",
            field=models.CharField(
                default=31, max_length=256, verbose_name="Whats App"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="contactus",
            name="email",
            field=models.EmailField(max_length=256, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="contactus",
            name="instagram",
            field=models.CharField(max_length=256, verbose_name="Instagram"),
        ),
        migrations.AlterField(
            model_name="contactus",
            name="phone_number",
            field=models.CharField(max_length=16, verbose_name="Phone"),
        ),
        migrations.DeleteModel(
            name="ContactUsBody",
        ),
    ]
