# Generated by Django 5.0.6 on 2024-07-15 14:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("site_settings", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aboutus",
            options={"verbose_name": "درباره ما", "verbose_name_plural": "درباره ما"},
        ),
        migrations.AlterModelOptions(
            name="cleaningservicepet",
            options={
                "verbose_name": "سرویس های پت",
                "verbose_name_plural": "سرویس های پت",
            },
        ),
        migrations.AlterModelOptions(
            name="contactus",
            options={"verbose_name": "تماس با ما", "verbose_name_plural": "تماس با ما"},
        ),
    ]
