# Generated by Django 5.0.6 on 2024-07-18 09:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("site_settings", "0002_alter_aboutus_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkingHours",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("saturday", models.CharField(max_length=256, verbose_name="شنبه")),
                ("sunday", models.CharField(max_length=256, verbose_name="یکشنبه")),
                ("monday", models.CharField(max_length=256, verbose_name="دوشنبه")),
                ("tuesday", models.CharField(max_length=256, verbose_name="سه شنبه")),
                (
                    "wednesday",
                    models.CharField(max_length=256, verbose_name="جهارشنبه"),
                ),
                ("thursday", models.CharField(max_length=256, verbose_name="پنجشنبه")),
                ("friday", models.CharField(max_length=256, verbose_name="جمعه")),
            ],
            options={
                "verbose_name": "ساعات کاری",
                "verbose_name_plural": "ساعات کاری",
            },
        ),
    ]
