# Generated by Django 5.0.6 on 2024-06-04 17:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("site_settings", "0002_remove_aboutus_body_remove_aboutus_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CleaningServicePet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "haircut",
                    models.TextField(
                        max_length=4096, verbose_name="توضیحات کوتاه کردن مو سگ و گربه"
                    ),
                ),
                (
                    "nail_trimming",
                    models.TextField(
                        max_length=4096,
                        verbose_name="توضیحات کوتاه کردن ناخن سگ و گربه",
                    ),
                ),
            ],
        ),
    ]
